name: Build APK

on:
  push:
    branches: [ main, основной ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Build with Buildozer
      uses: ArtemGovorov/buildozer-action@v1
      with:
        command: buildozer android debug
        repository_root: .

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
        
