name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Buildozer
      run: |
        # Устанавливаем права на папку для docker-контейнера
        sudo chown -R $USER:$USER .
        # Запускаем сборку
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
        
